# Generated by Django 5.0.4 on 2024-05-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='eventDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='eventCategories',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='eventEndTime',
            field=models.CharField(default='12:00 PM', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='eventStartTime',
            field=models.CharField(default='12:00 PM', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
